general:
  update_interval_ticks: 20

webhooks:
  new_day: "VERGI_GUNU_WEHBOOK_URL"
  new_town: "YENI_KASABA_OLUSTUGUNDA_URL"
  default_username: "MC-TR ğŸ¤–" # Wehbook ismi
  embed_logo_url: "https://cdn.discordapp.com/attachments/1144773610477735976/1308849175785504778/mctr.png?ex=673f7048&is=673e1ec8&hm=4e6651ea932d1b35de4a01c3008a4710e18011885bc83303b6b3f6868ef43ea4&" #Embed URL

messages:
  new_town:
    embed_title: "ğŸ¡ Yeni Bir Kasaba Kuruldu!"
    embed_description: "**%town_name%** kasabasÄ±, **%mayor_name%** tarafÄ±ndan **%world_name%** dÃ¼nyasÄ±nda kuruldu! ğŸš€"
    embed_color: "00FF00"
    embed_logo: "https://cdn.discordapp.com/attachments/1144773610477735976/1308849175785504778/mctr.png?ex=673f7048&is=673e1ec8&hm=4e6651ea932d1b35de4a01c3008a4710e18011885bc83303b6b3f6868ef43ea4&"

  new_day_report:
    title: "ğŸ“Š GÃ¼nlÃ¼k Towny Raporu"
    embed_title: "ğŸ“‹ GÃ¼nlÃ¼k Ä°statistikler"
    total_taxes: "ğŸ’° Toplanan Toplam Vergiler: **%total_taxes%**"
    richest_town: "ğŸ† En Zengin Kasaba: **%richest_town%** (Bakiye: **%richest_balance%**) ğŸ’¸"
    poorest_town: "ğŸ’” En Fakir Kasaba: **%poorest_town%** (Bakiye: **%poorest_balance%**) ğŸª™"
    unpaid_towns: "ğŸš¨ Vergisini Ã–deyemeyen Kasabalar: **%unpaid_towns%**"
    all_paid: "âœ”ï¸ TÃ¼m kasabalar vergilerini Ã¶dedi. ğŸ‘"
    embed_color: "FFDD00"
    footer_text: "Towny GÃ¼nlÃ¼k Ä°statistikleri ğŸ“…"
    footer_icon: "https://cdn.discordapp.com/attachments/1144773610477735976/1308849175785504778/mctr.png?ex=673f7048&is=673e1ec8&hm=4e6651ea932d1b35de4a01c3008a4710e18011885bc83303b6b3f6868ef43ea4&"
